//
//  PacketCodes.h
//  FerrariQuiz
//
//  Created by Gabi Durican on 03.07.2013.
//  Copyright (c) 2013 Gabi Durican. All rights reserved.
//

#ifndef FerrariQuiz_PacketCodes_h
#define FerrariQuiz_PacketCodes_h

typedef enum {
    NETWORK_HEARTBEAT,
    NETWORK_STARTGAME,
    NETWORK_ANSWER,
    NETWORK_GAMEOVER,
    NETWORK_DISCONNECT,
    NETWORK_SEED,
    NETWORK_REQUESTSTART,
    NETWORK_PASSWORD,
    NETWORK_OKPASSWORD,
    NETWORK_WRONGPASSWORD,
    NETWORK_SERVERSTARTEDGAME,
    NETWORK_NEXTQUESTION,
    NETWORK_WASFIRST,
    NETWORK_WASSECOND,
    NETWORK_RECONNECT,
    NETWORK_TIMEEXPIRED,
    NETWORK_PLAYERCOLOR,
    NETWORK_WON,
    NETWORK_LOST,
    NETWORK_DRAW,
    NETWORK_RESTARTGAME,
    NETWORK_LEAVEGAME,
    NETWORK_ENABLESTARTBUTTON,
    NETWORK_COUNTDOWNTIMER,
    NETWORK_ANSWERINGTIMER,
    NETWORK_HASANSWEREDTIMER,
    NETWORK_UPDATE_SCORES
} PacketCode;

#endif
